### PR TITLE
Add wine and alcohol shops

### PR DESCRIPTION
**Pull request by rmarianski**
Refs #448

Migration required:

```sql
UPDATE planet_osm_polygon SET
    mz_poi_min_zoom = mz_calculate_poi_level("aerialway", "aeroway", "amenity", "barrier", "craft", "highway", "historic", "leisure", "lock", "man_made", "natural", "office", "power", "railway", "rental", "shop", "tourism", "waterway", way_area)
    WHERE shop IN ('alcohol', 'wine');

UPDATE planet_osm_point SET
    mz_poi_min_zoom = mz_calculate_poi_level("aerialway", "aeroway", "amenity", "barrier", "craft", "highway", "historic", "leisure", "lock", "man_made", "natural", "office", "power", "railway", "rental", "shop", "tourism", "waterway", 0::real)
    WHERE shop IN ('alcohol', 'wine');
```

@zerebubuth could you review please?

### CODE REVIEW

**Comment by zerebubuth** [comment]
:+1: code looks good - migration is missing the "rental" parameter to `mz_calculate_poi_level`.

**Comment by rmarianski** [comment]
Great catch on the migration! I updated the migration in the description.

**Comment by rmarianski** [comment]
And rebased off latest master to resolve conflicts.

**Comment by nvkelso** [comment]
@sensescape We'll need 2 new icons (or one combo) for **alcohol** (versus & or) **wine**.

**Pull request merged**
