### PR TITLE
Add wof l10n names

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/mapzen/vector-datasource/issues/418

@zerebubuth could you review please?

### CODE REVIEW

**Comment by zerebubuth** [comment]
:+1:

**Comment by rmarianski** [comment]
Added tests for new iso-639-3 behavior in 4848780.

**Comment by rmarianski** [comment]
Added tests for lookups and country code suffixes in 75e86f3.

**Comment by nvkelso** [comment]
Looking good :)

**Pull request merged**
