### PR TITLE
Include highway=footway|pedestrian for polys only

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/mapzen/vector-datasource/issues/776

@nvkelso could you review please?

Migration required is:
```sql
UPDATE planet_osm_line
  SET mz_landuse_min_zoom = mz_calculate_min_zoom_landuse(planet_osm_line.*)
  WHERE
    highway IN ('pedestrian', 'footway');
```

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM

**Comment by rmarianski** [comment]
Restricting `aeroway` and `man_made` features to polygons in 8a7dde0.

**Comment by rmarianski** [comment]
Does it hurt to have it though? Happy to remove it but I think it might be easier to understand if we can have the rule be that all `aeroway`s need to be polygons.

**Comment by nvkelso** [comment]
You're right, I don't think having them in there will hurt. But it's also confusing to have them in there when we're pretty sure they aren't guarding against real problems. 

It's not clear to me where these rules originate, besides on the OSM wiki, e.g.:

screen shot 2016-05-02 at 15 35 33

**Comment by rmarianski** [comment]
Updated in 3388ecd.

**Pull request merged**
