### PR TITLE
Update mz_calculate_landuse_min_zoom function call

### PR DESCRIPTION
**Pull request by rmarianski**
@zerebubuth could you review please?

### CODE REVIEW

**Comment by zerebubuth** [comment]
Ooops... must have missed that one, sorry.

:+1:

**Comment by nvkelso** [comment]
What issue does this PR link up with?

**Comment by rmarianski** [comment]
One didn't exist. I ran into it locally when setting up a new database of north america.

@nvkelso should I create a new issue and link to it from here?

**Comment by nvkelso** [comment]
Yes, please.

**Comment by rmarianski** [comment]
Closes https://github.com/mapzen/vector-datasource/issues/512

**Pull request merged**
