### PR TITLE
Include aeroway tag for kind=gate

### PR DESCRIPTION
**Pull request by rmarianski**
Refs #454
Depends on https://github.com/mapzen/TileStache/pull/109

### CODE REVIEW

**Comment by nvkelso** [comment]
@rmarianski Can you attach before/after screenshots, please?

**Comment by zerebubuth** [comment]
Connects to #454.

**Comment by zerebubuth** [comment]
Screenshots on #454.

**Comment by nvkelso** [comment]
LGTM

**Pull request merged**
