### PR TITLE
Clarify docs for segregated property

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/mapzen/vector-datasource/pull/760/files/a32c8a6ee2a0eab89638d5a13a218fe30731e2ed#r61586659

@nvkelso this look ok? Or did you have something else in mind?

### CODE REVIEW

**Comment by zerebubuth** [comment]
Looks like the [most common values](http://taginfo.openstreetmap.org/keys/segregated#values) are `yes` and `no`. Do we strip the `no` values? If so, probably worth just saying something like "Present on paths allowing both pedestrian and bicycle traffic with the value `yes` when pedestrian traffic is segregated from bicycle traffic."

**Comment by rmarianski** [comment]
At the moment we're only just exposing the value on the feature. Should we only include it if its value is `yes`?

**Comment by nvkelso** [comment]
Yeah, agree we should be stripping the `no` value (the property should only be present when it's se to `yes`). That's more in line with what we do for `oneway`, etc.

Something like this for docs? (Riffing on Matt's proposal):

```
Set to `yes` when a path allows both pedestrian and bicycle traffic, but when
pedestrian traffic is segregated from bicycle traffic.
```

Is this property on more `highway` types than `path`?

**Comment by zerebubuth** [comment]
> Is this property on more `highway` types than `path`?

It's currently on all road types, since it could appear anywhere there's a segregated foot/cycle path, including on the sidewalk of another type of road. But in North America, it only appears on these `highway` values:

```
   highway    | num  
--------------+------
 cycleway     | 1556
 path         |  244
 footway      |   84
 service      |   10
 tertiary     |    6
 construction |    5
 pedestrian   |    5
 secondary    |    4
 trunk        |    3
 residential  |    3
 track        |    3
              |    2
 steps        |    1
```

I am intrigued as to where the segregated steps are, though...

**Comment by nvkelso** [comment]
Haha :)

I think it's okay to say "path" in this context (instead of road or way), since we're already grouping (cycleway,  path, footway) into `kind:path` and that's where almost all the tags are.

**Comment by rmarianski** [comment]
Updated the logic in 3cdbc9a, and the docs in 02ce1d5.

**Comment by nvkelso** [comment]
Neat use of expression in the YAML!

**Comment by zerebubuth** [comment]
Oh, I thought we were stripping out all the tags with the value `no` later on in the pipeline... I must have been mistaken.

**Pull request merged**
