### PR TITLE
Add address points to buildings layer.

### PR DESCRIPTION
**Pull request by zerebubuth**
Refs #181.

Adds address point features to buildings layer. At present, doesn't do address line interpolation, nor expose the address interpolation lines.

Before:

address_points_before

After:

address_points_after

### CODE REVIEW

**Comment by nvkelso** [comment]
Cool! 

/cc @rmarianski 
Do we need to be selecting all the extra attributes in `queries/buildings.jinja2`? I'm not opposed to some/all of them, but should we collapse some of them into `landuse_kind` like we did for the roads intercut?

**Comment by rmarianski** [comment]
That's a good point. Are you thinking of coalescing the `amenity`, `shop`, and `tourism` properties? The others look significant on their own right to me.

https://github.com/mapzen/vector-datasource/blob/5fb743a6f4e957e1c128bbca0e529026198b45e3/queries/buildings.jinja2#L2-L26

**Comment by nvkelso** [comment]
Are the total list of exported attributes on address and building features comparable? Should they be? 

I would expect there to be *more* attributes on buildings than on addresses. For instance, it doesn't seem worthwhile to export building shape attributes on the address points at all. And we should coalesce the typical list of keys into the generic kinds namespace to be consistent with our other feature classes.

**Comment by zerebubuth** [comment]
As I understand it, each jinja2 template is a single query, and the selected attributes have to be the same across all `union`ed sub-queries. Have I misunderstood? Are you suggesting dropping some attributes in the processing stages?

I would generally expect to put address points in a separate layer from buildings. The geometry (point / polygon) is completely different, the attributes are pretty different, and the style applied to them is going to be pretty different.

**Comment by rmarianski** [comment]
> As I understand it, each jinja2 template is a single query, and the selected attributes have to be the same across all unioned sub-queries. Have I misunderstood? Are you suggesting dropping some attributes in the processing stages?

We usually handle that by unioning the list of properties, and just setting them to null in the query itself for the query where it's irrelevant. We drop all properties where the value is null pretty early on in the pipeline.

**Comment by nvkelso** [comment]
Here's an example of the nulling Rob mentioned from the places layer:

https://github.com/mapzen/vector-datasource/blob/master/queries/places.jinja2#L9-L15

**Comment by zerebubuth** [comment]
@nvkelso I've dropped it down to only selecting `addr_housenumber`, `addr_street`, `name`, `id` and `amenity`, `shop` and `tourism` -- these last 3 are almost always NULL anyway, and it might make it easier to show a proper icon for these if they're on the address. Review, please?

**Comment by nvkelso** [comment]
LGTM. 

We're already not collapsing the `amenity`, `shop`, `tourism` keys into a single `kind`, but that doesn't need to be fixed in this issue.

**Comment by nvkelso** [comment]
See also: 

* https://github.com/mapzen/vector-datasource/issues/200

**Pull request merged**
