### PR TITLE
Initial changelog for v0.9.0

### PR DESCRIPTION
**Pull request by rmarianski**
@nvkelso I scanned through the commits to generate this initial list. Can you make any necessary updates to it?

### CODE REVIEW

**Comment by nvkelso** [comment]
Yep, moving assignment to me.

**Comment by nvkelso** [comment]
Back to Rob for review.

**Comment by rmarianski** [comment]
Made some minor edits. :+1:

**Comment by nvkelso** [comment]
Good catches (not sure why Mou didn't preview some of those errors to me!). Merging.

**Pull request merged**
