### PR TITLE
Update README to reflect new setup

### PR DESCRIPTION
**Pull request by rmarianski**
Refs #233

### CODE REVIEW

**Comment by rmarianski** [comment]
@nvkelso Could you review please?

**Comment by nvkelso** [comment]
I'm generally fine with this change, but shouldn't we mention TileStache somewhere?

It seems like [installation instructions](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service) should make that mention, but it doesn't currently make any reference to our TileStache fork (integration-1).

**Comment by rmarianski** [comment]
@nvkelso I added an update that mentions TileStache in the wiki.

https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#install-python-dependencies

**Comment by nvkelso** [comment]
LGTM, thanks.

**Comment by musicformellons** [comment]
Clear now, thanks!

**Pull request merged**
