### PR TITLE
fixes #593 for early paths

### LINKED ISSUE #593: Show highway=path at zoom 13
Thinking about an outdoor style, the convention is to show path features at **zoom 13**. 

(We're currently showing them at zoom 14.)

### PR DESCRIPTION
**Pull request by nvkelso**
* connects to #593 by moving many "path" like ways to zoom 13 and even zoom 12 and 11 depending on their significance. 
* restore names on paths at zooms 14 and z15
* remove bogus highway=minor and highway=footpath
* [tests] add tests for early zoom highway=path, =footway, =step
* [docs]  update layer reference to indicate earlier zooms for select paths;

### CODE REVIEW

**Comment by nvkelso** [comment]
Preview:

screen shot 2016-04-05 at 17 10 46

screen shot 2016-04-05 at 17 11 39

**Comment by rmarianski** [comment]
:+1:

**Comment by zerebubuth** [comment]
Are there test / docs changes needed for this?

**Comment by nvkelso** [comment]
Updated preview images:

z11 (SF):
sf_z11

z12 (SF):
sf_z12

z13 (SF):
sf_z13

z11 (Yosemite):
yosemite_z11

z12 (Yosemite):
yosemite_z12

z13 (Yosemite):
yosemite_z13

Note: SF zoom 11 shows weird dots with labels, that's an MVT file format funk unrelated to this change.

**Comment by nvkelso** [comment]
WARNING: This is missing more complicated trigger updates for relation complications.

**Comment by nvkelso** [comment]
I've confirmed that the import does bring in the relations into the planet osm lines table, so we'll properly already be tracking tile expires for the impacted ways. But we still need to update the trigger. Over to @rmarianski.

**Comment by rmarianski** [comment]
Added the trigger in d6865c0. @nvkelso, @zerebubuth Could you review that please?

**Comment by rmarianski** [comment]
Also updated when the trigger runs in 0dcf56b.

**Comment by zerebubuth** [comment]
:+1:

**Comment by rmarianski** [comment]
Turns out that we need to use triggers for each insert/update/delete. Change was made in cc46a6c.

**Pull request merged**
